#!/usr/bin/env node
/*
 * patch-add-pl.cjs
 *
 * Adds a complete Polish (pl) translation block to src/translations/index.js.
 * Polish was the only one of the 12 supported locales missing from LANG_MAP,
 * which is why the dashboard fell back to English when "polski" was selected
 * (getTranslations merges the selected lang over `en`; with no `pl` key the
 * merge is just `en`).
 *
 * Idempotent: guarded by the PL_BLOCK_V1 sentinel. Safe to re-run.
 * No .bak files (git is the safety net).
 *
 * Usage:
 *   node patch-add-pl.cjs [path/to/src/translations/index.js]
 * Defaults to ./src/translations/index.js
 */

'use strict';

var fs = require('fs');
var path = require('path');

var SENTINEL = 'PL_BLOCK_V1';

var TARGET = process.argv[2] || path.join(process.cwd(), 'src', 'translations', 'index.js');

// The complete Polish block. Object literal text inserted verbatim as a new
// `pl: { ... },` entry inside LANG_MAP. Covers every key present in `en`.
var PL_BLOCK = [
  "",
  "  /* " + SENTINEL + " */",
  "  pl: {",
  "    advice_1_title: \"Radzenie sobie z głodem w danej chwili\",",
  "    advice_1_body: \"Gdy pojawia się głód, wypróbuj zasadę 15 minut: odłóż działanie o 15 minut. Głód jest jak fala — narasta i opada. Rozprosz się krótkim spacerem, zimnym napojem lub rozmową z kimś.\",",
  "    advice_2_title: \"Rozpoznawanie wyzwalaczy głodu\",",
  "    advice_2_body: \"Zapisuj, kiedy głód jest najsilniejszy — pora dnia, miejsce, emocja lub sytuacja społeczna. Rozpoznawanie wzorców to pierwszy krok do proaktywnego radzenia sobie z nimi.\",",
  "    advice_3_title: \"Obniżony nastrój a używanie substancji\",",
  "    advice_3_body: \"Obniżony nastrój i używanie substancji często się wzajemnie wzmacniają. Gdy nastrój spada, skontaktuj się z kimś zaufanym zamiast sięgać po substancję. Nawet krótka rozmowa może zmienić twój stan.\",",
  "    advice_4_title: \"Budowanie rutyny poprawiającej nastrój\",",
  "    advice_4_body: \"Małe codzienne nawyki — 10-minutowy spacer, poranne światło słoneczne czy regularny posiłek — mogą stabilizować nastrój w czasie bardziej niezawodnie niż duże, sporadyczne wysiłki.\",",
  "    advice_5_title: \"Sen a powrót do zdrowia\",",
  "    advice_5_body: \"Sen to czas, gdy mózg się regeneruje. Dąż do stałej pory snu, unikaj ekranów 30 minut przed snem i utrzymuj pokój chłodny i ciemny. Zły sen zwiększa głód następnego dnia.\",",
  "    advice_6_title: \"Co zaburza sen podczas zdrowienia\",",
  "    advice_6_body: \"Alkohol i stymulanty fragmentują sen, nawet jeśli wydają się pomagać zasnąć. W miarę jak organizm się dostosowuje, jakość snu zwykle znacznie się poprawia w ciągu tygodni.\",",
  "    advice_7_title: \"Konsekwentne przyjmowanie leków\",",
  "    advice_7_body: \"Przepisane leki działają najlepiej, gdy są przyjmowane o tej samej porze każdego dnia. Ustaw przypomnienie w telefonie i trzymaj leki w widocznym miejscu, by stały się częścią rutyny.\",",
  "    advice_8_title: \"Rozmowa z lekarzem o lekach\",",
  "    advice_8_body: \"Jeśli masz obawy dotyczące skutków ubocznych, zapisz je przed wizytą. Nigdy nie przerywaj leczenia bez wcześniejszej konsultacji z lekarzem.\",",
  "    advice_9_title: \"Co oznacza dobrostan w zdrowieniu\",",
  "    advice_9_body: \"Dobrostan to nie tylko brak objawów — obejmuje poczucie celu, więzi i drobne rzeczy, na które można czekać. Zdrowienie idzie najlepiej, gdy budujesz życie, którym chcesz żyć.\",",
  "    advice_10_title: \"Aktywność fizyczna a dobrostan\",",
  "    advice_10_body: \"Nawet lekka aktywność fizyczna — 20-minutowy spacer trzy razy w tygodniu — zmniejsza lęk, poprawia sen i obniża głód. Nie potrzebujesz siłowni.\",",
  "    advice_11_title: \"Stres a ryzyko nawrotu\",",
  "    advice_11_body: \"Stres jest jednym z najczęstszych wyzwalaczy nawrotu. Określ dwa lub trzy największe źródła stresu i z wyprzedzeniem pomyśl o jednym praktycznym kroku dla każdego.\",",
  "    advice_12_title: \"Oddychanie w celu redukcji stresu\",",
  "    advice_12_body: \"Powolne oddychanie aktywuje przywspółczulny układ nerwowy i zmniejsza reakcję na stres w ciągu minut. Spróbuj wdychać przez 4 sekundy, wstrzymać przez 4, wydychać przez 6.\",",
  "    advice_13_title: \"Rozmowa z zaufanymi osobami\",",
  "    advice_13_body: \"Izolacja zwiększa ryzyko. Posiadanie przynajmniej jednej osoby, wobec której możesz być szczery — co do tego, jak naprawdę się czujesz — jest jednym z najsilniejszych czynników ochronnych w zdrowieniu.\",",
  "    advice_14_title: \"Wyznaczanie granic w relacjach\",",
  "    advice_14_body: \"To w porządku mówić nie sytuacjom lub osobom, które zagrażają twojemu zdrowieniu. Możesz być bezpośredni bez bycia ostrym: „Nie jestem teraz w stanie tego zrobić”.\",",
  "    advice_15_title: \"Co robić po nawrocie\",",
  "    advice_15_body: \"Nawrót to nie porażka — to informacja. Spróbuj bez oceniania ustalić, co się stało, porozmawiaj z kimś i jak najszybciej wróć do swojej rutyny.\",",
  "    advice_16_title: \"Świętowanie małych postępów\",",
  "    advice_16_body: \"Zdrowienie obejmuje setki małych decyzji każdego dnia. Docenianie ich — nawet samo zauważenie dobrego wyboru — buduje pewność siebie i rozpęd w czasie.\",",
  "    advice_17_title: \"Proszenie o pomoc\",",
  "    advice_17_body: \"Proszenie o pomoc to oznaka samoświadomości, nie słabości. Czy to lekarz, infolinia, czy ktoś bliski — wczesny kontakt jest zawsze lepszy niż czekanie.\",",
  "    advice_18_title: \"Planowanie na trudne chwile\",",
  "    advice_18_body: \"Pomyśl o sytuacjach, które są dla ciebie najtrudniejsze, i ułóż prosty plan: do kogo zadzwonisz, co zrobisz, dokąd pójdziesz? Posiadanie planu zmniejsza szansę, że stres doprowadzi do użycia.\",",
  "    cravings: \"Głód\",",
  "    wellbeing: \"Dobrostan\",",
  "    substances: \"Substancje\",",
  "    substancesUsed: 'Użyte substancje',",
  "    scorePct: 'Wynik %',",
  "    avgAmount: 'Śr. ilość',",
  "    daysUsed: 'Dni używania',",
  "    questionnaireRadar: 'Radar kwestionariuszy',",
  "    substanceProfile: 'Profil substancji',",
  "    recoveryProfile: 'Profil zdrowienia',",
  "    spiderDiagrams: 'Diagramy pajęcze',",
  "    gender: 'Płeć',",
  "    heightLabel: 'Wzrost',",
  "    weightBmi: 'Waga i BMI',",
  "    patient: 'Pacjent',",
  "    patientReport: 'Raport pacjenta',",
  "    sideEffects: \"Skutki uboczne\",",
  "    weight: \"Waga\",",
  "    amount: \"Ilość\",",
  "    loading: \"Ładowanie…\",",
  "    relevantAdvice: \"Istotne porady\",",
  "    noRelevantAdvice: \"Pacjent nie oznaczył jeszcze żadnej porady jako istotnej.\",",
  "    relevant: \"Istotne\",",
  "    avgCravings: \"Śr. głód\",",
  "    avgWellbeing: \"Śr. dobrostan\",",
  "    totalRecords: \"Łączna liczba wpisów\",",
  "    substancesAllTime: \"Wszystkie substancje\",",
  "    noSubstances: \"Nie zarejestrowano substancji\",",
  "    days: \"dni\",",
  "    bmi: \"BMI\",",
  "    noWeight: \"Nie zarejestrowano wagi\",",
  "    noLogThisDay: \"Brak wpisu dla tego dnia.\",",
  "    noQuestionnaire: \"Nie wypełniono\",",
  "    answers: \"Surowe dane\",",
  "    partA: \"Część A\",",
  "    total: \"Razem\",",
  "    threshold: \"Próg\",",
  "    prescribedMeds: \"Przepisane leki\",",
  "    noMedications: \"Nie zarejestrowano leków.\",",
  "    medicationHistory: \"Stosowanie leków z wpisów\",",
  "    noMedHistory: \"Brak danych o lekach.\",",
  "    weightHistory: \"Historia wagi\",",
  "    noWeightHistory: \"Brak danych o wadze.\",",
  "    kg: \"kg\",",
  "    graphs: \"Wykresy\",",
  "    noData: \"Brak danych dla tego zakresu.\",",
  "    substancesByWeek: \"Używanie substancji tygodniowo\",",
  "    questionnaireScores: \"Wyniki kwestionariuszy\",",
  "    recentEntries: \"Ostatnie wpisy\",",
  "    noSubstancesLogged: \"Nie zarejestrowano substancji\",",
  "    medicationsTitle: 'Leki',",
  "    medicationsSubtitle: 'Wybierz wszystkie leki, które obecnie przyjmujesz',",
  "    myMedications: 'Moje leki',",
  "    commonMedications: 'Popularne leki na ADHD',",
  "    addCustom: 'Dodaj własny',",
  "    noCustomMeds: 'Brak własnych leków',",
  "    addMedication: 'Dodaj lek',",
  "    medicationName: 'Nazwa leku',",
  "    dosage: 'Dawkowanie',",
  "    frequency: 'Częstotliwość',",
  "    startDate: 'Data rozpoczęcia',",
  "    prescribedBy: 'Przepisane przez',",
  "    prescribedByHint: 'Nazwisko lekarza (opcjonalnie)',",
  "    saveMedication: 'Zapisz lek',",
  "    removeMedication: 'Usuń lek',",
  "    removeMedConfirm: 'Usuń',",
  "    searchMedications: 'Szukaj leków...',",
  "    noMedsSaved: 'Nie zapisano leków. Dodaj je w Moich lekach.',",
  "    freqOnceDaily: 'Raz dziennie',",
  "    freqTwiceDaily: 'Dwa razy dziennie',",
  "    freqThreeDaily: '3× dziennie',",
  "    freqWeekly: 'Tygodniowo',",
  "    freqAsNeeded: 'W razie potrzeby',",
  "    shareTabCode: 'Kod',",
  "    shareTabASRS: 'ASRS',",
  "    shareTabStudies: 'Badania',",
  "    shareDescription: 'Bezpieczny dostęp do twojego raportu na tej stronie:',",
  "    sharePersonalNotes: 'Udostępnij osobiste notatki',",
  "    codeExpired: 'Kod wygasł',",
  "    codeValidFor: 'Kod jest ważny przez 10 minut',",
  "    generateNewCode: 'WYGENERUJ NOWY KOD',",
  "    studiesTitle: 'Badania i opracowania',",
  "    studiesSubtitle: 'Najnowsze recenzowane badania dotyczące ADHD.',",
  "    focusSubtitle: '1 = doskonałe skupienie, 5 = brak możliwości skupienia',",
  "    impulsivitySubtitle: '1 = bardzo spokojny, 5 = bardzo impulsywny',",
  "    sleepSubtitle: 'Jak spałeś tej nocy?',",
  "    tasksSubtitle: 'Jak produktywny byłeś dzisiaj?',",
  "    taskLabels: ['Wszystko zrobione','Większość','Część','Niewiele','Nic'],",
  "    nothingToSave: 'Nic do zapisania',",
  "    fillOneField: 'Wypełnij przynajmniej jedno pole.',",
  "    deleteLog: 'Usuń wpis',",
  "    deleteLogConfirm: 'Czy na pewno chcesz usunąć ten wpis?',",
  "    delete: 'Usuń',",
  "    asrsWhatIs: 'Czym jest ASRS?',",
  "    asrsWhyMatters: 'Dlaczego to ważne?',",
  "    asrsHowWorks: 'Jak to działa?',",
  "    asrsWhatIsBody: 'ASRS-v1.1 to oficjalne, zatwierdzone przez WHO narzędzie przesiewowe do ADHD u dorosłych.',",
  "    asrsWhyMattersBody: 'ADHD często pozostaje nierozpoznane u dorosłych. Regularne samooceny pomagają śledzić wzorce objawów w czasie.',",
  "    asrsHowWorksBody: 'Odpowiadasz na 18 pytań o częstotliwość objawów ADHD. Część A (6 pytań) to przesiew kliniczny — wynik 14 lub wyższy uznaje się za istotny.',",
  "    asrsInfoExplanation: 'Ten kwestionariusz pomaga opisać, jak się czujesz i co objawy ADHD uniemożliwiają ci robić. Stanowi solidną podstawę do rozmowy z lekarzem.',",
  "    yourAsrsRecord: 'Twój zapis ASRS',",
  "    appName: 'FocusApp',",
  "    tagline: 'Dzienny tracker ADHD',",
  "    last30days: 'Ostatnie 30 dni',",
  "    daysLogged: 'Zarejestrowane dni',",
  "    avgMood: 'Śr. nastrój',",
  "    avgFocus: 'Śr. skupienie',",
  "    avgSleep: 'Śr. sen',",
  "    medication: 'Leki',",
  "    myData: 'MOJE DANE',",
  "    myDiary: 'MÓJ DZIENNIK',",
  "    shareData: 'UDOSTĘPNIJ DANE',",
  "    myMedication: 'MOJE LEKI',",
  "    dailyLog: 'DZIENNY WPIS',",
  "    editTodayLog: 'EDYTUJ DZISIEJSZY WPIS',",
  "    login: 'Zaloguj się',",
  "    register: 'Utwórz konto',",
  "    email: 'E-mail',",
  "    confirmEmail: 'Potwierdź e-mail',",
  "    age: 'Wiek',",
  "    pinCode: 'Kod PIN',",
  "    createPin: 'Utwórz',",
  "    pinCreated: 'Utworzono ✓',",
  "    alreadyAccount: 'Masz już konto?',",
  "    noAccount: 'Nie masz konta?',",
  "    signUp: 'ZAREJESTRUJ SIĘ',",
  "    forgotPin: 'ZAPOMNIAŁEŚ PIN-U?',",
  "    yourDiary: 'Twój osobisty\\nDziennik Focus',",
  "    acceptTerms: 'Akceptuję',",
  "    termsLink: 'Regulamin',",
  "    includingPrivacy: '(w tym Politykę prywatności)',",
  "    consentText: 'Wyrażam zgodę na przetwarzanie przez KBB Medic AS informacji o moim zdrowiu, zgodnie z polityką prywatności. Wiem, że mogę wycofać tę zgodę.',",
  "    createAccount: 'UTWÓRZ KONTO',",
  "    choosePin: 'Wybierz PIN',",
  "    choosePinSub: 'Wprowadź 4-cyfrowy PIN, aby zabezpieczyć aplikację',",
  "    confirmPin: 'Potwierdź PIN',",
  "    confirmPinSub: 'Wprowadź PIN ponownie, aby potwierdzić',",
  "    enterPin: 'Wprowadź PIN',",
  "    enterPinSub: 'Wprowadź PIN, aby kontynuować',",
  "    pinNoMatch: 'Kody PIN nie pasują',",
  "    pinNoMatchSub: 'Spróbuj ponownie.',",
  "    ok: 'OK',",
  "    welcomeTitle: 'Witaj! 👋',",
  "    welcomeText1: 'FocusApp pomaga śledzić codzienny nastrój, skupienie, sen i energię — dając tobie i lekarzowi jasny obraz tego, jak ADHD wpływa na twoje życie.',",
  "    welcomeText2: 'Zapisuj raz dziennie, obserwuj wzorce w czasie i dziel się spostrzeżeniami z lekarzem.',",
  "    letsStart: 'ZACZNIJMY',",
  "    howDidYouFeel: 'Jak się czułeś?',",
  "    adhdSymptoms: 'Objawy ADHD',",
  "    sleepTasks: 'Sen i zadania',",
  "    medicationSec: 'Leki',",
  "    notes: 'Notatki',",
  "    mood: 'Nastrój',",
  "    energy: 'Energia',",
  "    focus: 'Skupienie',",
  "    impulsivity: 'Impulsywność',",
  "    sleepQuality: 'Jakość snu',",
  "    tasksCompleted: 'Ukończone zadania',",
  "    screenTime: 'Czas przed ekranem',",
  "    tookMedToday: 'Przyjąłem leki dzisiaj',",
  "    howWasYourDay: 'Jak minął twój dzień?',",
  "    saveLog: 'Zapisz wpis',",
  "    save: 'Zapisz',",
  "    cancel: 'Anuluj',",
  "    errorSave: 'Nie udało się zapisać wpisu',",
  "    logDay: 'Zapisz dzień',",
  "    missingFields: 'Brakujące pola',",
  "    missingFieldsMsg: 'Oceń nastrój, skupienie, sen, energię i impulsywność przed zapisaniem.',",
  "    medicationTaken: 'Przyjęto leki',",
  "    medicationNotes: 'Notatki o lekach…',",
  "    triggers: 'Wyzwalacze',",
  "    writeAboutDay: 'Napisz coś o swoim dniu…',",
  "    activity: 'Aktywność',",
  "    screenTimeH: 'Czas przed ekranem (godz.)',",
  "    triggerStress: 'Stres',",
  "    triggerPoorSleep: 'Zły sen',",
  "    triggerCaffeine: 'Kofeina',",
  "    triggerAlcohol: 'Alkohol',",
  "    triggerScreenOverload: 'Za dużo ekranu',",
  "    triggerNoExercise: 'Brak ćwiczeń',",
  "    triggerSkippedMed: 'Pominięto lek',",
  "    triggerNoise: 'Hałas',",
  "    triggerSocialOverload: 'Przeciążenie społeczne',",
  "    triggerDiet: 'Dieta',",
  "    scores: {",
  "      mood:        ['Bardzo dobry', 'Dobry', 'OK', 'Zły', 'Bardzo zły'],",
  "      focus:       ['Doskonałe', 'Dobre', 'OK', 'Rozproszone', 'Brak skupienia'],",
  "      sleep:       ['Świetny', 'Dobry', 'OK', 'Słaby', 'Okropny'],",
  "      energy:      ['Pełen energii', 'Energiczny', 'OK', 'Zmęczony', 'Wyczerpany'],",
  "      impulsivity: ['Bardzo spokojny', 'Spokojny', 'Pewne impulsy', 'Impulsywny', 'Bardzo impulsywny'],",
  "    },",
  "    scoreBest: '1 = Najlepszy',",
  "    scoreWorst: '5 = Najgorszy',",
  "    scoreNone: 'Brak',",
  "    scoreLight: 'Lekki',",
  "    scoreMedium: 'Umiarkowany',",
  "    scoreHeavy: 'Ciężki',",
  "    scoreExtreme: 'Ekstremalny',",
  "    scorePoor: 'Słaby',",
  "    scoreSevere: 'Poważny',",
  "    calendar: 'Kalendarz',",
  "    diary: 'Dziennik',",
  "    dayView: 'Dzień',",
  "    monthView: 'Miesiąc',",
  "    daysLoggedShort: 'Zarejestrowane dni',",
  "    avgScore: 'Śr. wynik',",
  "    missing: 'Brak',",
  "    scoreBreakdown: 'Podział wyników',",
  "    scoreVeryLow: 'Bardzo niski',",
  "    scoreLow: 'Niski',",
  "    scoreModerate: 'Umiarkowany',",
  "    scoreGood: 'Dobry',",
  "    scoreExcellent: 'Doskonały',",
  "    months: ['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'],",
  "    weekdays: ['Pon','Wt','Śr','Czw','Pt','Sob','Niedz'],",
  "    noLogs: 'Brak wpisów',",
  "    settings: 'Ustawienia',",
  "    chooseGender: 'Wybierz płeć',",
  "    female: 'Kobieta',",
  "    male: 'Mężczyzna',",
  "    undefined: 'Nieokreślona',",
  "    personalSettings: 'Ustawienia osobiste',",
  "    language: 'Język',",
  "    pin: 'PIN',",
  "    changePin: 'Zmień PIN',",
  "    termsConditions: 'Regulamin',",
  "    about: 'O aplikacji',",
  "    appearance: 'Wygląd',",
  "    signOut: 'Wyloguj się',",
  "    signOutClearPin: 'Wyloguj się i usuń PIN',",
  "    signOutMsg: 'Możesz zalogować się ponownie e-mailem i PIN-em.',",
  "    clearPinMsg: 'To usunie twój PIN z tego urządzenia.',",
  "    change: 'Zmień',",
  "    view: 'Zobacz',",
  "    saved: 'Zapisano',",
  "    profileUpdated: 'Twój profil został zaktualizowany.',",
  "    saveChanges: 'Zapisać zmiany?',",
  "    unsavedChanges: 'Masz niezapisane zmiany. Czy chcesz je zapisać?',",
  "    discard: 'Odrzuć',",
  "    languageTitle: 'Język',",
  "    registerAsrsRecord: 'Zarejestruj zapis ASRS',",
  "    asrsTitle: 'ASRS-v1.1',",
  "    asrsSubtitle: 'Skala samooceny ADHD u dorosłych',",
  "    asrsIntroBody: 'To zalecane przez WHO narzędzie przesiewowe do ADHD u dorosłych. Odpowiedz na 18 pytań o to, jak się czułeś przez ostatnie 6 miesięcy.',",
  "    asrsQuestions: '18 pytań • Część A (6) + Część B (12)',",
  "    asrsTime: 'Zajmuje około 5 minut',",
  "    asrsSaved: 'Wyniki zapisane w twojej historii',",
  "    asrsDisclaimer: 'Zalecane przez WHO • Nie jest diagnozą kliniczną',",
  "    asrsFullDisclaimer: 'Ta ocena ma charakter wyłącznie informacyjny i nie zastępuje profesjonalnej porady medycznej, diagnozy ani leczenia.',",
  "    asrsPartA: 'Część A',",
  "    asrsPartB: 'Część B',",
  "    asrsPartASub: 'Pytania przesiewowe (6)',",
  "    asrsPartBSub: 'Pytania rozszerzone (12)',",
  "    asrsSeeResults: 'Zobacz wyniki',",
  "    asrsRemaining: 'pozostałych pytań',",
  "    asrsTakeAgain: 'Wykonaj ponownie',",
  "    asrsThreshold: 'Próg przesiewowy Części A',",
  "    asrsAnswerBreakdown: 'Podział odpowiedzi',",
  "    asrsHighTitle: 'Wysoce zgodne z ADHD',",
  "    asrsHighBody: 'Twój wynik Części A sugeruje objawy wysoce zgodne z ADHD u dorosłych. Rozważ omówienie tych wyników z pracownikiem służby zdrowia.',",
  "    asrsModTitle: 'Umiarkowanie zgodne z ADHD',",
  "    asrsModBody: 'Twoje wyniki sugerują pewne objawy zgodne z ADHD. Pracownik służby zdrowia może pomóc to wyjaśnić.',",
  "    asrsLowTitle: 'Nie w pełni zgodne z ADHD',",
  "    asrsLowBody: 'Twoje obecne wyniki nie wskazują silnie na objawy ADHD. Kontynuuj śledzenie w czasie, by uzyskać pełniejszy obraz.',",
  "    asrsPartAScore: 'Wynik Części A\\n(maks. 24)',",
  "    asrsTotalScore: 'Wynik całkowity\\n(maks. 72)',",
  "    asrsNever: 'Nigdy',",
  "    asrsRarely: 'Rzadko',",
  "    asrsSometimes: 'Czasami',",
  "    asrsOften: 'Często',",
  "    asrsVeryOften: 'Bardzo często',",
  "    asrsQ1: 'Jak często masz trudność z dokończeniem ostatnich szczegółów projektu, gdy najtrudniejsze części są już zrobione?',",
  "    asrsQ2: 'Jak często masz trudność z uporządkowaniem rzeczy, gdy musisz wykonać zadanie wymagające organizacji?',",
  "    asrsQ3: 'Jak często masz problemy z zapamiętaniem spotkań lub zobowiązań?',",
  "    asrsQ4: 'Gdy masz zadanie wymagające dużo myślenia, jak często unikasz lub odkładasz rozpoczęcie?',",
  "    asrsQ5: 'Jak często wiercisz się lub poruszasz dłońmi czy stopami, gdy musisz długo siedzieć?',",
  "    asrsQ6: 'Jak często czujesz się nadmiernie aktywny i zmuszony do działania, jakby napędzał cię silnik?',",
  "    asrsQ7: 'Jak często popełniasz nieuważne błędy, gdy pracujesz nad nudnym lub trudnym projektem?',",
  "    asrsQ8: 'Jak często masz trudność z utrzymaniem uwagi przy nudnej lub powtarzalnej pracy?',",
  "    asrsQ9: 'Jak często masz trudność ze skupieniem się na tym, co mówią ludzie, nawet gdy mówią bezpośrednio do ciebie?',",
  "    asrsQ10: 'Jak często gubisz rzeczy lub masz trudność ze znalezieniem rzeczy w domu lub w pracy?',",
  "    asrsQ11: 'Jak często rozpraszają cię aktywność lub hałas wokół ciebie?',",
  "    asrsQ12: 'Jak często opuszczasz swoje miejsce na spotkaniach lub w innych sytuacjach, w których oczekuje się, że pozostaniesz na miejscu?',",
  "    asrsQ13: 'Jak często czujesz się niespokojny lub poruszony?',",
  "    asrsQ14: 'Jak często masz trudność z odprężeniem się i relaksem, gdy masz czas dla siebie?',",
  "    asrsQ15: 'Jak często zdarza ci się mówić za dużo w sytuacjach towarzyskich?',",
  "    asrsQ16: 'Jak często kończysz zdania osób, z którymi rozmawiasz?',",
  "    asrsQ17: 'Jak często masz trudność z czekaniem na swoją kolej w sytuacjach, które tego wymagają?',",
  "    asrsQ18: 'Jak często przerywasz innym, gdy są zajęci?',",
  "    adviceTitle: 'Porady',",
  "    adviceAll: 'WSZYSTKIE',",
  "    adviceRelevantForMe: 'ISTOTNE DLA MNIE',",
  "    adviceReadMore: 'Czytaj więcej >',",
  "    adviceBack: 'Wstecz',",
  "    adviceBadgeNew: 'Nowe',",
  "    adviceBadgeViewed: 'Przejrzane',",
  "    adviceBadgeRelevant: 'Istotne',",
  "    adviceRelevantNote: 'Ta porada jest oznaczona jako istotna na podstawie zarejestrowanych objawów.',",
  "    adviceMarkRelevant: 'To jest istotne dla mnie',",
  "    adviceNoRelevant: 'Otwórz poradę i zaznacz „To jest istotne dla mnie”, aby zobaczyć ją tutaj.',",
  "    asrsWhatTitle: 'Czym jest ASRS?',",
  "    asrsWhatBody: 'Skala samooceny ADHD u dorosłych (ASRS-v1.1) to oficjalne, zatwierdzone przez WHO narzędzie przesiewowe do ADHD u dorosłych. Powstało we współpracy ze Światową Organizacją Zdrowia i jest stosowane przez klinicystów na całym świecie.',",
  "    asrsWhyTitle: 'Dlaczego to ważne?',",
  "    asrsWhyBody: 'ADHD często pozostaje nierozpoznane u dorosłych. Regularne samooceny pomagają tobie i lekarzowi śledzić wzorce objawów w czasie, mierzyć skuteczność leczenia i prowadzić lepiej poinformowane rozmowy podczas wizyt.',",
  "    asrsHowTitle: 'Jak to działa?',",
  "    asrsHowBody: 'Odpowiadasz na 18 pytań o to, jak często doświadczasz konkretnych objawów związanych z ADHD. Część A (6 pytań) to przesiew kliniczny — wynik 14 lub wyższy uznaje się za istotny. Część B (12 pytań) daje pełniejszy obraz twojego profilu objawów.',",
  "    asrsChipQuestions: 'Pytania',",
  "    asrsChipTime: 'Do wypełnienia',",
  "    asrsChipEndorsed: 'Zatwierdzone',",
  "    asrsThresholdLabel: '14 = próg',",
  "    asrsNotComplete: 'Niekompletne',",
  "    recoverHeadline: 'Twoje zdrowienie',",
  "    recoverSubtitle: 'Opieka oparta na dowodach – dostępna, kiedy jej potrzebujesz.',",
  "    recoverDescription: 'Zdrowienie wygląda inaczej u każdego. Recover zapewnia ustrukturyzowane codzienne wpisy, śledzenie postępów i klinicznie zweryfikowane zasoby – abyś zawsze miał wsparcie, na które zasługujesz.',",
  "    soberStreak: 'Passa trzeźwości',",
  "    streakNow: 'z rzędu',",
  "    daySingular: 'dzień',",
  "    daysPlural: 'dni',",
  "    longest: 'Najdłuższa',",
  "    useDays: 'Użycie',",
  "    questionnairesShort: 'kwestionariusze',",
  "    sober: 'Trzeźwy',",
  "    date: 'Data',",
  "    records: 'wpisy',",
  "    range1Month: 'Ostatni 1 miesiąc',",
  "    range3Months: 'Ostatnie 3 miesiące',",
  "    range6Months: 'Ostatnie 6 miesięcy',",
  "    range9Months: 'Ostatnie 9 miesięcy',",
  "    rangeAll: 'Cały okres',",
  "    'highCravings': 'Silny głód',",
  "    'note': 'Notatka',",
  "    'recoveryProfile': 'Profil zdrowienia',",
  "    'substanceProfile': 'Profil substancji',",
  "    'questionnaireRadar': 'Radar kwestionariuszy',",
  "    'substanceMix': 'Rozkład substancji',",
  "    'amountOverTime': 'Ilość w czasie',",
  "    'dayOfWeekPattern': 'Wzorzec wg dnia tygodnia',",
  "    'moodCravingsWellbeing': 'Nastrój, głód i dobrostan',",
  "    'weightOverTime': 'Trend wagi',",
  "    'higherIsBetter': 'Wyżej = lepiej na wszystkich osiach',",
  "    'daysAndAvgPerSubstance': 'Dni używania i śr. ilość na substancję',",
  "    'percentOfMaxScore': '% maksymalnego wyniku',",
  "    'daysEachEffectLogged': 'Dni, w których odnotowano każdy skutek',",
  "    'daysUsedPerSubstance': 'Dni używania na substancję',",
  "    'dailyConsumption': 'Dzienne spożycie · 0 = trzeźwy',",
  "    'useRateByWeekday': 'Częstotliwość użycia wg dnia tygodnia',",
  "    'scaleOneToFive': 'Skala 1–5',",
  "    'totalAmount': 'Całkowita ilość',",
  "    'avgPerUseDay': 'Śr. / dzień użycia',",
  "    'peakDay': 'Szczyt',",
  "    'hardestDay': 'Najtrudniejszy dzień',",
  "    'easiestDay': 'Najłatwiejszy dzień',",
  "    'useRate': 'Częstotliwość użycia',",
  "    'count': 'Liczba',",
  "    'day': 'dzień',",
  "    'score': 'Wynik',",
  "    'daysUsed': 'Dni używania',",
  "    'avgAmount': 'Śr. ilość',",
  "    'patientProfile': 'Profil pacjenta',",
  "    'lowCravings': 'Niski głód',",
  "    'lowAmount': 'Niska ilość',",
  "    'soberDays': 'Dni trzeźwości',",
  "    'range': 'Okres',",
  "    'last': 'Ostatnie',",
  "    'allTime': 'Cały okres',",
  "    'entries': 'wpisy',",
  "    'notEnoughQuestionnaireData': 'Za mało danych z kwestionariuszy',",
  "    'needThreeSubstances': 'Potrzeba co najmniej 3 substancji do radaru',",
  "    'noUseInRange': 'Brak użycia substancji w tym okresie',",
  "    'noSideEffectsLogged': 'Brak skutków ubocznych w tym okresie',",
  "    'weekdaysShort': ['Pon', 'Wt', 'Śr', 'Czw', 'Pt', 'Sob', 'Niedz'],",
  "    'readiness': 'Gotowość do zmiany',",
  "    'soberStreaks': 'Okresy trzeźwości',",
  "    'streaksSubtitle': 'Bieżący okres, najdłuższy ciąg, mapa trzeźwy/użycie',",
  "    'currentStreak': 'Bieżący okres',",
  "    'longestStreak': 'Najdłuższy okres',",
  "    'soberDaysTotal': 'Łącznie dni trzeźwości',",
  "    'topStreaks': 'Najdłuższe okresy',",
  "    'ongoing': 'trwa',",
  "    'used': 'Użyto',",
  "    'patientReport': 'Raport pacjenta',",
  "    'patient': 'Pacjent',",
  "    'age': 'Wiek',",
  "    'gender': 'Płeć',",
  "    'heightLabel': 'Wzrost',",
  "    'weight': 'Waga',",
  "    'bmi': 'BMI',",
  "    'weightBmi': 'Waga i BMI',",
  "    'kg': 'kg',",
  "    'avgMood': 'Śr. nastrój',",
  "    'avgCravings': 'Śr. głód',",
  "    'avgWellbeing': 'Śr. dobrostan',",
  "    'totalRecords': 'Łączna liczba wpisów',",
  "    'soberStreak': 'Okres trzeźwości',",
  "    'daySingular': 'dzień',",
  "    'daysPlural': 'dni',",
  "    'streakNow': 'z rzędu',",
  "    'longest': 'Najdłuższy',",
  "    'useDays': 'Użyto',",
  "    'spiderDiagrams': 'Diagramy pajęcze',",
  "    'questionnaires': 'Kwestionariusze',",
  "    'noQuestionnaire': 'Nie ukończono',",
  "    'scorePct': 'Wynik %',",
  "    'substancesUsed': 'Substancje',",
  "    'noSubstancesMonth': 'Nie zarejestrowano substancji',",
  "    'substancesMonth': 'Podsumowanie substancji',",
  "    'relevantAdvice': 'Istotne porady',",
  "    'history': 'Wpisy',",
  "    'exportPdfReport': 'Eksportuj raport PDF',",
  "    'downloadPdf': 'Pobierz PDF',",
  "    'generating': 'Generowanie…',",
  "    'renderingCharts': 'Renderowanie wykresów…',",
  "    'capturingDiagrams': 'Przechwytywanie diagramów…',",
  "    'pdfFailed': 'Nie udało się wygenerować PDF. Spróbuj ponownie.',",
  "    'dateRange': 'Zakres dat',",
  "    'records': 'wpisy',",
  "    'questionnairesShort': 'kwestionariusze',",
  "    'monthSummary': 'Statystyki okresu',",
  "    'wellnessIndex': 'Wskaźnik dobrostanu',",
  "    'last30Days': 'Ostatnie 30 dni',",
  "    'improving': 'poprawa',",
  "    'declining': 'pogorszenie',",
  "    'stable': 'stabilnie',",
  "    'tierThriving': 'Rozkwit',",
  "    'tierStable': 'Stabilnie',",
  "    'tierWatch': 'Obserwacja',",
  "    'tierAtRisk': 'Ryzyko',",
  "    'tierCritical': 'Krytyczny',",
  "    'compSobriety': 'Trzeźwość',",
  "    'compCravings': 'Głód',",
  "    'compMoodWellbeing': 'Nastrój/dobrostan',",
  "    'compMentalHealth': 'Zdrowie psychiczne',",
  "    'compEngagement': 'Zaangażowanie',",
  "    'attentionNeeded': 'Obserwacja',",
  "    'vsPrevMonth': 'vs. poprzedni miesiąc',",
  "    'compLowCravings': 'Niski głód',",
  "    'compMentalWellness': 'Dobrostan psychiczny',",
  "    'lastLog': 'Ostatni wpis',",
  "    'logToday': 'Zapisano dzisiaj',",
  "    'logYesterday': 'Zapisano wczoraj',",
  "    'daysAgo': 'dni temu',",
  "    'showDetail': 'Pokaż ostatni wpis vs typowy',",
  "    'hideDetail': 'Ukryj szczegóły',",
  "    'outsideMonth': 'poza wybranym miesiącem',",
  "    'lastUse': 'Ostatnie użycie',",
  "    'bestDay': 'Najlepszy dzień',",
  "    'worstDay': 'Najgorszy dzień',",
  "    'totalLogs': 'Łącznie wpisów',",
  "    'never': 'Nigdy',",
  "    'timeline': 'Oś czasu',",
  "    'usedShort': 'Użyto',",
  "    'filterAll': 'Wszystkie',",
  "    'filterUseDays': 'Dni użycia',",
  "    'filterSoberDays': 'Dni trzeźwości',",
  "    'filterHighCravings': 'Głód ≥4',",
  "    'filterNotes': 'Z notatkami',",
  "    'filterSideEffects': 'Skutki uboczne',",
  "    'filterMilestones': 'Kamienie milowe',",
  "    'milestone': 'kamień milowy',",
  "    'streakBroken': 'Okres przerwany',",
  "    'searchNotes': 'Szukaj w notatkach lub substancjach',",
  "    'noMatchingLogs': 'Żaden wpis nie pasuje do filtra.',",
  "    'scores': 'Wartości',",
  "    'lifetimeBest': 'Rekord życiowy',",
  "    'avgStreak': 'Średni okres',",
  "    'streakContextNewBest': 'Nowy rekord osobisty',",
  "    'streakContextNearBest': 'Zbliża się do rekordu',",
  "    'streakContextAboveAvg': 'Powyżej średniej',",
  "    'streakContextBuildingUp': 'Buduje się',",
  "    'flaggedEvents': 'Oznaczone zdarzenia',",
  "    'noFlaggedEvents': 'Brak oznaczonych zdarzeń w tym okresie',",
  "    'flagSuicidalIdeation': 'Wskazane myśli samobójcze',",
  "    'flagPhq9q9': 'PHQ-9 pytanie 9',",
  "    'flagHighCravings': 'Utrzymujący się silny głód',",
  "    'flagStreakBroken': 'Przerwany okres trzeźwości',",
  "    'flagLogGap': 'Przerwa w zapisach',",
  "    'flagNoRecentLog': 'Brak ostatniego wpisu',",
  "    'flagAuditHigh': 'AUDIT w zakresie szkodliwym',",
  "    'peak': 'szczyt',",
  "    'endedOn': 'zakończono',",
  "    'monthlyTrends': 'Średnie miesięczne',",
  "    'alcohol': 'Alkohol',",
  "    'cannabis': 'Marihuana',",
  "    'cocaine': 'Kokaina',",
  "    'heroin': 'Heroina',",
  "    'amphetamine': 'Amfetamina',",
  "    'methamphetamine': 'Metamfetamina',",
  "    'mdma': 'MDMA',",
  "    'ecstasy': 'Ecstasy',",
  "    'ketamine': 'Ketamina',",
  "    'lsd': 'LSD',",
  "    'psilocybin': 'Psylocybina',",
  "    'mushrooms': 'Grzyby',",
  "    'opioids': 'Opioidy',",
  "    'benzodiazepines': 'Benzodiazepiny',",
  "    'nicotine': 'Nikotyna',",
  "    'tobacco': 'Tytoń',",
  "    'ghb': 'GHB',",
  "    'inhalants': 'Wziewne',",
  "    'noneThisMonth': 'brak w tym miesiącu',",
  "    'prescribed': 'przepisane',",
  "    'takenLower': 'przyjęte',",
  "    'noAdvice': 'Nie wyświetlono jeszcze żadnych porad dla tego pacjenta.',",
  "    'noneSurfaced': 'brak wyświetlonych',",
  "    'items': 'szt.',",
  "    'advice': 'Porada',",
  "    'yearAtAGlance': 'Rok w skrócie',",
  "    'noLog': 'Brak wpisu',",
  "    'clickToJump': 'Kliknij dzień, aby przejść',",
  "    'monthsShort': ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru'],",
  "    'streakContextAverage': 'W średniej',",
  "    'wellnessOverTime': 'Dobrostan w czasie',",
  "    'trajectory': 'Trajektoria',",
  "    'best': 'Najlepszy',",
  "    'worst': 'Najgorszy',",
  "    'readMore': 'Czytaj więcej',",
  "    'sectionBigPicture': 'Szeroki obraz',",
  "    'sectionDayByDay': 'Dzień po dniu',",
  "    'sectionClinical': 'Kliniczne',",
  "    'sectionProfile': 'Profil pacjenta',",
  "    'sectionTrends': 'Trendy',",
  "    'strongestArea': 'najmocniejszy obszar',",
  "    'weakestArea': 'wymaga uwagi',",
  "    'insightStreakMonth': 'Obecnie utrzymuje passę 30+ dni — ważny kamień milowy.',",
  "    'insightStreakTwoWeek': 'Obecnie w 2-tygodniowym+ okresie trzeźwości — trwały postęp.',",
  "    'insightStreakWeek': 'Trwa tygodniowa passa — nabieranie rozpędu.',",
  "    'insightStreakNewBest': 'Obecnie najdłuższa zarejestrowana passa pacjenta.',",
  "    'insightStreakBroken': 'Niedawno przerwał dłuższą passę — zalecane bliskie wsparcie.',",
  "    'insightHardestVsEasiest': 'to dzień najwyższego ryzyka',",
  "    'insightHighRisk': 'wykazuje podwyższoną częstotliwość użycia',",
  "    'insightAllSober': 'Nie wykryto użycia w żaden dzień tygodnia w tym okresie.',",
  "    'insightConsistentPattern': 'Częstotliwość użycia jest dość stała w różne dni tygodnia.',",
  "    'insightTopSideEffect': 'jest najczęściej zgłaszany',",
  "    'ofAllReports': 'wszystkich zgłoszeń',",
  "    'ofMax': 'z maks.',",
  "    'elevatedScore': 'podwyższony',",
  "    'withinRange': 'w typowym zakresie',",
  "    'insightMostlySober': 'dni było trzeźwych — silny okres zdrowienia',",
  "    'insightMajoritySober': 'dni było trzeźwych',",
  "    'insightPolysubstance': 'Wzorzec wielosubstancyjny',",
  "    'appearMostFrequently': 'pojawiają się najczęściej',",
  "    'daysOfUse': 'dni używania',",
  "    'insightMoodImproving': 'Nastrój się poprawia',",
  "    'insightMoodDeclining': 'Nastrój się pogarsza',",
  "    'insightMoodStable': 'Nastrój stabilny w całym okresie.',",
  "    'insightWeightStable': 'Waga stabilna w całym okresie.',",
  "    'points': 'punktów',",
  "    'overPeriod': 'w okresie',",
  "    'noAlerts': 'Brak alertów',",
  "    'noAlertsBody': 'Wszystkie ostatnie wskaźniki w oczekiwanych zakresach.',",
  "    'itemToReview': 'pozycja do przeglądu',",
  "    'itemsToReview': 'pozycji do przeglądu',",
  "    'consecutiveDays': 'kolejnych dni',",
  "    'streak': 'okres trzeźwości',",
  "    'lastLogged': 'Ostatnio zapisano',",
  "    'likelyDependence': 'wskazuje na prawdopodobne uzależnienie od alkoholu',",
  "    'severityUrgent': 'pilne',",
  "    'severityWarning': 'ostrzeżenie',",
  "    'wellness': 'Dobrostan',",
  "    'useDaysShort': 'Dni użycia',",
  "    'moodTrend': 'Trend nastroju',",
  "    'keyFindings': 'Kluczowe ustalenia',",
  "    'findingHighRiskDay': 'to dzień najwyższego ryzyka',",
  "    'vsLower': 'vs',",
  "    'onOtherDays': 'w inne dni',",
  "    'findingMoodImproving': 'Nastrój się poprawia',",
  "    'findingMoodDeclining': 'Nastrój się pogarsza',",
  "    'findingStreakMonth': 'Obecnie utrzymuje',",
  "    'findingStreakTwoWeek': 'Obecnie w',",
  "    'findingStreakWeek': 'Obecnie w',",
  "    'findingAuditElevated': 'Podwyższony wynik AUDIT',",
  "    'findingPhq9Elevated': 'PHQ-9 podwyższony',",
  "    'moderateDepression': 'zakres depresji umiarkowanej do ciężkiej',",
  "    'findingPolysubstance': 'Wzorzec wielosubstancyjny',",
  "    'cravingsMoodLeadLag': 'Głód vs Nastrój — Lead/Lag',",
  "    'crossCorrelationAnalysis': 'Korelacja krzyżowa przy opóźnieniach ±3 dni',",
  "    'notEnoughDataForLeadLag': 'Za mało danych do analizy korelacji',",
  "    'leadLagAxisLabel': 'Dni nastrój wyprzedza ←  →  Głód wyprzedza',",
  "    'insightLeadLagNoCorrelation': 'Brak istotnej korelacji między nastrojem a głodem.',",
  "    'insightLeadLagSameDay': 'Nastrój i głód poruszają się razem tego samego dnia',",
  "    'insightLeadLagMoodLeads': 'Nastrój przewiduje głód',",
  "    'insightLeadLagCravingsLeads': 'Głód poprzedza zmiany nastroju',",
  "    'aheadOf': 'przed',",
  "    'strong': 'silna',",
  "    'moderate': 'umiarkowana',",
  "    'weak': 'słaba',",
  "    'compareVsPrior': 'vs poprzedni okres',",
  "    'thisVsPriorPeriod': 'Ten okres vs poprzedni',",
  "    'categoryMood': 'Nastrój',",
  "    'categoryRecovery': 'Zdrowienie',",
  "    'categoryWellbeing': 'Dobrostan',",
  "    'categoryMedication': 'Leki',",
  "    'categorySleep': 'Sen',",
  "    'categoryCravings': 'Głód',",
  "    'weeklyAverages': 'Średnie tygodniowe (pon–niedz)',",
  "    'weekShort': 'Tydz.',",
  "    'logged': 'zapisano',",
  "  },",
  ""
].join('\n');

function main() {
  if (!fs.existsSync(TARGET)) {
    console.error('ERROR: target file not found: ' + TARGET);
    process.exit(1);
  }

  var src = fs.readFileSync(TARGET, 'utf8');

  if (src.indexOf(SENTINEL) !== -1) {
    console.log('Already patched (' + SENTINEL + ' present). No changes made.');
    return;
  }

  // Find the closing of LANG_MAP: the `};` that terminates
  //   const LANG_MAP = { ... };
  // We anchor on the export that immediately follows, which is stable:
  //   export function getTranslations(lang) {
  var anchor = src.indexOf('export function getTranslations');
  if (anchor === -1) {
    console.error('ERROR: could not locate getTranslations anchor. Aborting (no changes).');
    process.exit(1);
  }

  // Walk backwards from the anchor to the closing `};` of LANG_MAP.
  var head = src.slice(0, anchor);
  var closeIdx = head.lastIndexOf('};');
  if (closeIdx === -1) {
    console.error('ERROR: could not locate LANG_MAP closing brace. Aborting (no changes).');
    process.exit(1);
  }

  // Insert the pl block just before the `};`.
  var before = src.slice(0, closeIdx);
  var after = src.slice(closeIdx);

  // Ensure the preceding content ends cleanly; the existing last locale block
  // ends with "  },\n" so we append our block, then the original "};".
  var patched = before + PL_BLOCK + '\n' + after;

  fs.writeFileSync(TARGET, patched, 'utf8');
  console.log('Patched: added complete Polish (pl) block to ' + TARGET);
}

main();
